version: '3.4'

services:
  sqldata:
    image: mcr.microsoft.com/mssql/server:2022-latest 
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5433:1433"
    volumes:
      - sqldata:/var/opt/mssql

  subscription-api:
   image: subscription-api:latest
   build:
     context: .
     dockerfile: SubscriptionManagementWebApi/Dockerfile
   environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Kestrel__Endpoints__HTTP__Url=http://0.0.0.0:80
      - ConnectionStrings__MSSQL=Server=sqldata;Initial Catalog=SubscriptionManagement;User Id=sa;Password=Pass@word;Encrypt=False;TrustServerCertificate=true
      - PORT=80
   ports:
      - "9000:80"
      - "9001:81"
   depends_on:
     - sqldata

volumes:
  sqldata:
    external: false

